# Generated by Django 5.2.4 on 2025-08-01 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('room', 'Room'), ('self_contain', 'Self Contain'), ('1_bedroom', '1 Bedroom Flat'), ('2_bedroom', '2 Bedroom Flat'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='HouseListing_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('house_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.houselisting')),
            ],
        ),
    ]
